Section2　天気の画像をreloadButtonを押すことで変わるようにしました。
Syunprograming1/yumemiTrainnig pull request #2
Opened 2021-03-29 07:42 UTC by Syunprograming1

Modelを作りAPIの処理を実装しました。
天気の画像が変わる処理を書きました。enumで判断するようにしています。

心配な部分
cocoaMVCを意識しましたが、Modelの書き方がこんな感じでいいのか心配です。

2021-03-29 15:22 UTC, ykws reviewed
PR ありがとうございます。
コメントさせて頂いたのでご確認をお願いします。
内容がわかりにくい箇所はコメント頂けたら補足します。

- `.gitignore` に関する変更を別 PR に
- `enum` 定義の見直し
- 未定義の状態はエラーとして扱う
- ViewController で状態を持たないように

2021-03-29 15:22 UTC, ykws commented on YumemiTraining/Model/YumemiWeatherAPIModel.swift
> +            return .sunny
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)

未定義の状態はエラーとして扱うべきなので、握り潰さないようにする習慣としておいた方が良いです。
例えばですが、 `.sunny` が返ってくるので安心していたら、実は `default` で `.sunny` を返していて握り潰していたという状態だと、 API との設計不備があったとしても気付きにくく、バグの温床になりやすいです。

2021-03-29 15:22 UTC, ykws commented on YumemiTraining/ViewController.swift
> +    var yumemiWeatherAPIModel = YumemiWeatherAPIModel()
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)

```suggestion
```

データの扱いを Model に閉じ込めようという意図はとても良いと思います。
ただ、それを ViewController で持ってしまうと状態管理していることになっているため、コード全体を読んで Model の状態を把握する必要が生じていると感じました。

例えばですが、 ViewController で `var` を持たずに Model からの更新を View に反映させるにはどうしたら良いかという観点で見直してもらえると ViewController で状態を気にせずに書けると思います。

2021-03-30 01:02 UTC, Syunprograming1 commented
レビューありがとうございます！
修正します。

2021-03-30 02:22 UTC, Syunprograming1 commented
Modelを持たないためにNotificationCenterを使いました

心配な部分
NotificationでModelを持っていないことになるのか
enumのrawValueのguard let がこんな感じでいいのか

2021-03-30 03:44 UTC, el-hoshino requested changes
CocoaMVCの書き方自体はそれほど違和感はないと思いますが、static func使うとDIが難しくなるので、そうするとテストが書きにくかったりする問題が出てくるから、普通はあまりおすすめはしません

あと注意しないといけないのは、「Model」という単語はコンテキストによって指してるものが全然違うので、そういう曖昧さを回避したい場合はもっと別の言葉を選んだほうがいいこともあります、たとえば今回の場合なら `WeatherUsecase`  とかの方がいいかもしれません

参考： https://qiita.com/takasek/items/70ab5a61756ee620aee6
（内容が難しいので今全部理解しなくても大丈夫です、あくまで「Model」はコンテキストによって違うよ、という意識を持っていただけたらと思います

2021-03-30 03:44 UTC, el-hoshino commented on YumemiTraining/Extension/NotificationNameExtension.swift
> +    static let weatherReload = Notification.Name("weatherReload")
[nits]
これを `Notification.Name` に入れるよりも、`YumemiWeatherAPIModel` に入れた方がいいかもしれません；

例として、アプリがバックグラウンドに入ったよ、という通知は `UIApplication.didEnterBackgroundNotification` で定義されてるように、この `didEnterBackgroundNotification: Notification.Name` は `UIApplication` の中で定義されています；この方が `Notification.Name` 自体に余計な責務を押し付けずにすみます

また名前自体も、「これから取得する」のか「既に取得済み」なのかわかりづらいので、`weatherDidReload` の方がいいですね

2021-03-30 03:44 UTC, el-hoshino commented on YumemiTraining/Model/YumemiWeatherAPIModel.swift
> +class  YumemiWeatherAPIModel {
[nits]
継承する予定がないクラスはとりあえず `final class` にしちゃいましょう

2021-03-30 03:44 UTC, el-hoshino commented on YumemiTraining/Model/YumemiWeatherAPIModel.swift
> +    static var simpleWeather = WeatherType(rawValue: YumemiWeather.fetchWeather())
[nits]
外から変更を受けて欲しくないプロパティーは `private(set)` でセッターを隠しちゃいましょう

ところで、`simple` はどういう意図で使いましたか？

2021-03-30 03:44 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +    var weather = WeatherType.sunny
[must]
既に `YumemiWeatherAPIModel` があるなら、VCでこの状態を持たさない方がいいでしょう；UIKit自体はSwiftUIみたいに「Single Source of Truth」のようなコンセプトは明示されていませんが、一般的にも同じことを指す状態が散らかってしまうと、どれが正規なのかがわからなくなってしまうので；たとえばこの場合も、起動時に即 `sunny` が代入されていますか、本当に `sunny` が正しいのか？という問題が発生しています

2021-03-30 03:44 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +        changeWeatherImageViewImage(weatherType: weather)
[nits]
上記のプロパティーの問題もあって、`viewDidLoad` で画像をセットしなくてもいいです、そもそもこの段階では正しい天気が取得できませんので

2021-03-30 03:44 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +        reloadButton.addTarget(self, action: #selector(reloadButtonDidTapped(_:)), for: .touchUpInside)
[must]
ボタンの動作に `didTap` のような名前をつけずに、何をやるかの名前をつけましょう（ちなみに `didTapped` は英文法の間違いです）

参考： https://qiita.com/bitpoetics/items/a63bd1d9afc0b3221890

2021-03-30 03:44 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +        notificationCenterRegister()
[nits]
他のメソッドは全てAPI Design Guideline通りにVO命名なのに、ここだけOV命名になってしまうと一貫性がなくなるのと、`notificationCenter` だと全ての通知を受信するかのように受け止めてしまいそうですので、`observeWeatherNotification` のような名前の方がいいでしょう

2021-03-30 03:44 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +        changeWeatherImageViewImage(weatherType: weather)
[must]
この一連の動作ですと、`simpleWeatherReload` 呼び出した直後に、APIModelの天気情報が更新済みでNotificationCenter通じてその新しい天気がVCのweatherにも更新されているという実態をVCが知ってる、ということになってしまいます。これは密結合になってしまうのと、一般的なWeb API呼び出しは非同期で結果が返ってくる（ネタバレになりますがこの課題も後々非同期呼び出しのセッションがあります）ので、この実装では通用しなくなります

正しくは：

1. ReloadButtonをタップしたら、APIModelに天気情報の更新だけ催す
2. APIModelが持ってる天気情報が更新されたよ、という通知を受け取ったら、その時初めて新しい天気の画像を更新

です

2021-03-30 05:18 UTC, Syunprograming1 commented on YumemiTraining/Model/YumemiWeatherAPIModel.swift
> +    static var simpleWeather = WeatherType(rawValue: YumemiWeather.fetchWeather())
areaで天気を取得する関数がAPIにあったので今後使い分けるかなと思い
simpleWeatherとareWeatherとかにしようと思ってsimpleにしました

2021-03-30 05:23 UTC, Syunprograming1 commented
レビューありがとうございます！
修正します。

2021-03-30 05:52 UTC, el-hoshino commented on YumemiTraining/Model/YumemiWeatherAPIModel.swift
> +    static var simpleWeather = WeatherType(rawValue: YumemiWeather.fetchWeather())
@Syunprograming1 なるほど、それで `areaWeather` はどんなプロパティーにする予定でしょうか？

2021-03-30 05:58 UTC, Syunprograming1 commented on YumemiTraining/Model/YumemiWeatherAPIModel.swift
> +    static var simpleWeather = WeatherType(rawValue: YumemiWeather.fetchWeather())
あんま考えず、とりあえず名前分けてみた感じです。
static var simpleWeather : WeatherType
みたいな感じかなと

2021-03-30 06:34 UTC, Syunprograming1 commented
修正しました。

心配なところ
：static を使わずにModelをViewControllerが持たないようにするのがわからず、結局 let weatherUseCase = WeatherUseCase()　で持つ感じになってしまった。
：変数がprivateだと取得できないので付けれなかった。

2021-03-30 07:58 UTC, Syunprograming1 commented
外から変化しない方がいいものをprivate(set)にしました

2021-03-30 09:07 UTC, watanavex reviewed
気になっところコメントしましたが、すでに完成度が高いですw
素晴らしい！

2021-03-30 09:07 UTC, watanavex commented on YumemiTraining/ViewController.swift
> +    private func changeWeatherImageViewImage(weatherType: WeatherType){
[imo]
名前がちょっと冗長？
仮引数名も利用して、文章っぽくなるようにするのがSwift的かなと。

`changeWeatherImage(for weatherType: WeatherType)` 
私だったらこんな風にするかなぁ🤔 

`private func setImageInWeatherImageView(imageName: String, color: UIColor)` も再検討してみても良いかも。

2021-03-30 09:07 UTC, watanavex commented on YumemiTraining/Model/WeatherUseCase.swift
> +    let weatherDidReloadNotification = Notification.Name("weatherReload")
[imo]
`weatherDidReloadNotification`
これはstaticで宣言するのが一般的です。
理由はNotificationCenterは送信側、受信側が相互にインスタンスを知らなくても通信ができることがメリットだからです。
インスタンスプロパティにしてしまうと、送信側のインスタンスを受信側が知る必要が出てきてしまいます。

2021-03-30 09:11 UTC, Syunprograming1 commented
レビューありがとうございます。
命名短く修正してみます。

2021-03-30 09:18 UTC, Syunprograming1 commented on YumemiTraining/Model/WeatherUseCase.swift
> +    let weatherDidReloadNotification = Notification.Name("weatherReload")
staticにした場合,　同じクラスの関数でその変数を使いたい時は
static func にするのか、それともクラス内でもWeatherUseCase.weatherDidReloadNotificationこういう感じで使用する方がいいですか？

2021-03-30 15:55 UTC, ykws reviewed
PR 修正ありがとうございます！
追加で気になった箇所をコメントしました。

- ベクター対応
- `enum` の最適化
- API 利用の前提の確認
- NotificationCenter の活用

2021-03-30 15:55 UTC, ykws commented on YumemiTraining/ViewController.swift
> +    @objc func reloadWeatherImageView(){
![badge](https://img.shields.io/badge/review-imo-orange.svg)

NotificationCenter を利用するなら、データも通知で受け取ることで疎結合になります。
WeatherUseCase で天気予報の状態を持つことは、要件としては含まれていないため、
天気予報の情報はインスタントな扱いで十分です。

求められている要件が何かを明快にし、それをよりシンプルに実現することが大事です。
これを意識しないとプログラムはどんどん複雑になってしまうので。

### 参考
[[Swift 5]NotificationCenterでデータ（値）の渡し方
](https://qiita.com/Cyemang/items/94f3ddc26649c797a3e4)

```suggestion
        NotificationCenter.default.addObserver(self, selector: #selector(reloadWeatherImageView(notification:), name: WeatherUseCase.weatherDidReloadNotification, object: nil)
    }
    
    @objc func reloadWeatherImageView(notification: NSNotification?) {
```

2021-03-31 01:18 UTC, Syunprograming1 commented
レビューありがとうございます！
修正します

2021-03-31 01:48 UTC, Syunprograming1 commented
修正しました
NotificationでWeather(天気)をやり取りするようにし、WeatherUseCaseでプロパティとして持つのをやめました。

2021-03-31 03:25 UTC, el-hoshino approved these changes
![LGTM](https://i.lgtm.fun/1c64.png)

2021-03-31 03:25 UTC, el-hoshino commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/xcode,swift
すでにgitignoreのブランチでこのファイル追加したから、このブランチからはこのファイルを消しても大丈夫ですー（微妙にファイルの内容が違うからコンフリクト出てます

2021-03-31 03:25 UTC, el-hoshino commented on YumemiTraining/Extension/NotificationNameExtension.swift
> +    static let weatherReload = Notification.Name("weatherReload")
[nits]
このファイルも消しちゃって大丈夫ですー

2021-03-31 03:25 UTC, el-hoshino commented on YumemiTraining/Model/WeatherUseCase.swift
> +        NotificationCenter.default.post(name: WeatherUseCase.weatherDidReloadNotification, object: nil, userInfo: ["weather": weather])
[nits]
自分自身の型を使うときは `Self` 使えるので便利ですー

```suggestion
        NotificationCenter.default.post(name: Self.weatherDidReloadNotification, object: nil, userInfo: ["weather": weather])
```

2021-03-31 05:00 UTC, Syunprograming1 commented
レビューありがとうございます。
消します！

2021-03-31 06:20 UTC, merged