Section3 fetchWeatherのエラー処理を追加、エラーによってアラートを表示
Syunprograming1/yumemiTrainnig pull request #5
Opened 2021-03-31 08:03 UTC by Syunprograming1

やったこと
APIのエラー処理
UIAlertControllerの実装、呼び出し

心配な点
：WeatherTypeへの変換時今までguard let で return していただけのものを　! で落とすようにした点
→rawValueが違う時点でコードがまずいからクラッシュさせるべきと考えました。

レビューお願いします！

2021-03-31 16:41 UTC, el-hoshino requested changes

2021-03-31 16:41 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +import YumemiWeather
[must]
こちらがVCなのに、APIのライブラリーに依存しているのは非常に危険な信号です、これはつまりプレゼンテーションロジックにドメインロジックが混ざった、ということを意味し、密結合に繋がります（解決法がすでに上のエラーハンドリングの話で述べた通り、APIのエラー型をVCに流さないようにすればOKです）

ちなみに、逆にドメインロジックの部品（Usecaseなど）がUIKitに依存してるのも、同じ危険信号です

プレゼンテーションロジックとドメインロジックの分離については、「presentation domain separation」や「関心の分離」などについてググってみるといいかもです

2021-03-31 16:41 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +            showAlert(alertMessage: "不明なエラー")
この書き方もいいですが、下記のように一つの型としてcatchして内部でswitchしてもいいです、このほうが網羅性がコンパイラーに保証されます：

```swift
catch let weatherError as YumemiWeatherError {
    switch weatherError {
    case .invalidParameterError:
        // ...
    }
}
```

2021-03-31 16:41 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +    private func getOkAlertAction() -> UIAlertAction {
[nits]
これはAPI Design Guideline的には `get` ではなく `make` の方がいいですね

参考： https://swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage

2021-03-31 16:41 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +        let okAction = UIAlertAction(title: "OK", style: .default, handler: { (UIAlertAction) in
[must]
ここで `@escaping` なクロージャがあるので、`[weak self]` で自分自身を弱参照でキャプチャーした方がいいです

参考： https://qiita.com/chino_tweet/items/6335c660a75d6da30bc4

実際の処理としては、`ViewController` は別にこの `UIAlertController` を直接参照持ってるわけではないので循環参照は起こりませんが、それでもVCのライフサイクル自体に影響を及ぼしかねないので、`@escaping` のクロージャを見ると、とりあえず必要な参照を弱参照でキャプチャーしてあげるのはいい習慣になります

2021-03-31 16:41 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +            self.dismiss(animated: true, completion: nil)
[must]
ここで `dismiss` したいのはおそらく `alert` かと思いますが、ここで実際 `dismiss` しようとしてるのは `ViewController` になります（`ViewController` がすでにRootViewControllerなのでdismissのしようがないから正しく動いてるように見えますが、バグです

ちなみに `handler` を `nil` にしても、アラートのボタンをタップするとiOSは自動的にアラートを閉じてくれます

2021-03-31 17:05 UTC, ykws reviewed
PR ありがとうございます！
コメントしましたので確認をお願いします。

2021-03-31 17:05 UTC, ykws commented on YumemiTraining/ViewController.swift
> +            try weatherUseCase.reloadWeather(area: area)
![badge](https://img.shields.io/badge/review-nits-green.svg)

前回指摘できれば良かったのですが、 `reload` という名前は View からの見え方であって、 UseCase としては、 `request` が自然だと感じました。 API に合わせて `fetch` でも良いと思います。

```suggestion
            try weatherUseCase.requestWeather(area: area)
```
```suggestion
            try weatherUseCase.fetchWeather(area: area)
```

2021-04-01 01:00 UTC, Syunprograming1 commented
レビューありがとうございます！
修正します。

2021-04-01 02:17 UTC, Syunprograming1 commented
修正しました。

心配な部分
Result のsuccess の部分
→successに何も入れない時こんな感じで良いのか

2021-04-01 03:01 UTC, ykws reviewed
PR 修正ありがとうございます！
コメントしたので確認をお願いします。

2021-04-01 04:52 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +        switch  weatherUseCase.fetchWeather(area: area) {
ですね、一貫性があるコードの方が望ましいと思います

2021-04-01 05:30 UTC, Syunprograming1 commented on YumemiTraining/ViewController.swift
> +        switch  weatherUseCase.fetchWeather(area: area) {
レビューありがとうございます！修正します

2021-04-01 06:26 UTC, el-hoshino approved these changes
もうだいぶコードの見通しは良くなってきたので、とりあえず大丈夫かと；いつまでも細かいところ修正していってもキリがないので後から直してもOKです
![LGTM](https://i.lgtm.fun/1bxj.png)

2021-04-01 06:26 UTC, el-hoshino commented on YumemiTraining/Model/WeatherUseCase.swift
> +    }
もうNotification出してないから、このメソッド名はもう内容にあってないですね 😅

2021-04-01 06:26 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +    private func switchAlert(weatherError: WeatherError){
```suggestion
    private func showAlert(weatherError: WeatherError){
```

2021-04-01 06:34 UTC, Syunprograming1 commented
レビューありがとうございます！
命名修正します。

2021-04-01 06:44 UTC, merged