Section6　起動時のViewControllerを追加し、Closeを押したら天気のVCを閉じる処理を追加
Syunprograming1/yumemiTrainnig pull request #6
Opened 2021-04-01 06:22 UTC by Syunprograming1

起動時のFirstViewControllerを追加
天気の画面（WeatherViewController)のCloseButtonを押した時の処理を追加しました。

Secttion3がレビュー待ちですが、Section4,5はAPIを差し替えるので先にコンフリクトが少なそうなSection6を先にやりました。
Section2をマージした後のmainからブランチを切っています。

レビューよろしくお願いします。

2021-04-01 06:55 UTC, el-hoshino requested changes

2021-04-01 06:55 UTC, el-hoshino commented on YumemiTraining/FirstViewController.swift
> +class FirstViewController: UIViewController {
[nits]
うーんこの名前は別にダメというわけではないですが、あまり馴染みがない命名ですね…

最初に出てくるダミーですので、`RootViewController` とか `InitialDummyViewController` とかの方がいいかもしれません

あと、`final` つけましょうね 👍

2021-04-01 06:55 UTC, el-hoshino commented on YumemiTraining/FirstViewController.swift
> +        navigateWeatherViewController()
[must]
`viewDidAppear` のオーバーライドは、親メソッドの呼び出しも必要です

参考： https://developer.apple.com/documentation/uikit/uiviewcontroller/1621423-viewdidappear

2021-04-01 06:55 UTC, el-hoshino commented on YumemiTraining/FirstViewController.swift
> +        let weatherViewController = self.storyboard?.instantiateViewController(withIdentifier: "WeatherViewController") as! WeatherViewController
[nits]
ここでは別に `weatherViewController` を `WeatherViewController` として使ったコード（`WeatherViewController` しかない機能の呼び出しなど）がないので、わざわざダウンキャストしなくても問題ないかと思います；

もし生成されたVCが `WeatherViewController` であることを保証したいなら、`weatherViewController` を作った後に、`assert(weatherViewController is WeatherViewController)` を入れればOKです；この場合、Debugビルドだけもし `weatherViewController` が `WeatherViewController` じゃなかった場合クラッシュします

参考： https://developer.apple.com/documentation/swift/1541112-assert

2021-04-01 06:55 UTC, el-hoshino commented on YumemiTraining/WeatherViewController.swift
> +// session3とコンフリクトしないように少し行を離す
多分ですが、改行を増やしても、差分の場所自体は変わってないので、コンフリクト起こるときは起こると思います 😅

2021-04-01 06:55 UTC, el-hoshino commented on YumemiTraining/WeatherViewController.swift
> +    @objc func closeFirstViewController() {
[nits]
こちら外からアクセスしないので、`@objc private func` でOKです；

また、`@objc` を `@IBAction` にすれば、Storyboardから直接ボタン動作を設定できるので、そうすると `setupCloseButton` も必要なくなります

2021-04-01 07:53 UTC, Syunprograming1 commented on YumemiTraining/FirstViewController.swift
> +class FirstViewController: UIViewController {
final忘れてました、、、
修正します

2021-04-01 07:58 UTC, Syunprograming1 commented
レビューありがとうございます！
修正します。

2021-04-01 12:38 UTC, el-hoshino requested changes

2021-04-01 12:38 UTC, el-hoshino commented on YumemiTraining/WeatherViewController.swift
> +    @IBAction func closeButtonDidTaped(_ sender: Any) {
あそうそうこれ指摘し忘れましたが、 #2 のレビューでも話しました気がしますが、ボタンの動作は `didTap` の名前はやめましょうね（あと `didTaped` は文法とスペル両方間違ってます 😅 

https://github.com/Syunprograming1/yumemiTrainnig/pull/2#discussion_r603754143

2021-04-01 12:39 UTC, el-hoshino commented
あと今コンフリクトが発生したままですので、最新のmainにRebaseしてコンフリクトを解消してから強制プッシュしてくださいー

2021-04-01 14:40 UTC, ykws reviewed
PR ありがとうございます。
気になった箇所をコメントしました。
@el-hoshino さんの指摘と矛盾するような内容も含まれていますが、
自分の中でどういう基準を持って、どの意見を採用するか決めてみてください。

2021-04-01 14:40 UTC, ykws commented on YumemiTraining/RootViewController.swift
> +
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)

`super` の呼び出しだけならなくて大丈夫ですよ。
`override` しなければ `super` 側で処理が実行されます。

```suggestion
```

2021-04-01 14:40 UTC, ykws commented on YumemiTraining/WeatherViewController.swift
> +    @IBAction func closeButtonDidTaped(_ sender: Any) {
![badge](https://img.shields.io/badge/review-imo-orange.svg)

https://github.com/Syunprograming1/yumemiTrainnig/pull/6#discussion_r605417575
この指摘での対応で `IBAction` に変更してもらっていますが、

一貫性の観点から、 `reloadButton` は `addTarget` でアクションを設定しているので、 `IBAction` or `addTarget` のどちらかに統一するようにしましょう。

2021-04-01 14:40 UTC, ykws commented on YumemiTraining/RootViewController.swift
> +        assert(weatherViewController is WeatherViewController)
![badge](https://img.shields.io/badge/review-imo-orange.svg)

https://github.com/Syunprograming1/yumemiTrainnig/pull/6#discussion_r605414840
この指摘での対応で `assert` を導入してもらっていますが、

現時点では、動的に表示画面が変わることはないので、 `assert` はやり過ぎのような気がしました。

2021-04-02 02:30 UTC, Syunprograming1 commented
レビューありがとうございます！
修正します

2021-04-02 07:24 UTC, Syunprograming1 commented
修正した後、main(Section3,4,5marge済)をrebaseしました。

2021-04-02 08:23 UTC, el-hoshino approved these changes
![LGTM](https://i.lgtm.fun/1ccg.png)

2021-04-02 08:25 UTC, merged