Session4 5　天気取得をjsonのAPIに変更、気温のラベル変化させる
Syunprograming1/yumemiTrainnig pull request #7
Opened 2021-04-01 08:24 UTC by Syunprograming1

Decodableを使用しました。
レビューよろしくお願いします。

2021-04-01 13:01 UTC, el-hoshino requested changes
週末時間あるときに、Swift API Design Guidelinesをじっくり読んでみましょう 💪 
https://swift.org/documentation/api-design-guidelines/

2021-04-01 13:01 UTC, el-hoshino commented on YumemiTraining/Model/Weather.swift
> +    var weather: String
[nits]
せっかく天気と気温をまとめた方を作ったから、ここで `weather` を `String` で持たせるのは勿体無いですね；これを `WeatherType` にすれば、後から色々処理しやすいです；

また、`weather` があくまで `Weather` の一つのプロパティーにすぎないのに、名前がダブるのは意図が分かりにくいので、どっちかの名前を変えた方がいいです（自分なら `WeatherType` を `Weather` の中に持ってきて `Type` か `Kind` にリネームして、このプロパティーもそれに合わせてリネームします）

2021-04-01 14:07 UTC, ykws reviewed
PR ありがとうございます。
@el-hoshino さんの指摘と同様にネーミングで気になった箇所をコメントしています。

プログラミング＝ネームミングと行っても過言ではないくらいなので、見直してみてください。
ネーミングに合わせて書き方も最適化されていくと思います。

2021-04-01 14:07 UTC, ykws commented on YumemiTraining/ViewController.swift
> +extension ViewController {
![badge](https://img.shields.io/badge/review-imo-orange.svg)

現在の規模でここまで `extension` を分けなくても良いかと思いましたが、
折角意味のある単位で分けていると思うので、
例えば、次のようなコメントでセクションに名前をつけるとよりわかりやすくなります。

```suggestion
// MARK: - Update Weather TempLabel

extension ViewController {
```

Xcode で次のように視覚化されます。

<img width="731" alt="スクリーンショット 2021-04-01 23 01 22" src="https://user-images.githubusercontent.com/5770480/113305764-53e98380-933e-11eb-853c-ab8056551ace.png">

2021-04-02 01:19 UTC, Syunprograming1 commented
レビューありがとうございます！
いろいろ修正します。

2021-04-02 01:21 UTC, Syunprograming1 commented on YumemiTraining/Model/WeatherUseCase.swift
> +            return .success(makeWeatherOfJson(weatherJsonString: weatherJsonString))
なるほどです。
逆に関数でどっちも返す感じでも一貫性になりますか？

2021-04-02 02:26 UTC, Syunprograming1 commented
![スクリーンショット 2021-04-02 11 24 04](https://user-images.githubusercontent.com/60774471/113373599-2a644280-93a6-11eb-9c44-5ef31a4680bf.png)
![スクリーンショット 2021-04-02 11 25 06](https://user-images.githubusercontent.com/60774471/113373602-2b956f80-93a6-11eb-8aeb-bae9ea868ed0.png)

修正しました
enumに天気の情報を寄せるようにしました

2021-04-02 04:11 UTC, el-hoshino commented on YumemiTraining/Model/Area.swift
> +struct Area: Codable {
[imo]
@ykws `Request` や `Response` で命名するのもアリといえばアリですが、その名前のままVCに伝搬したくないですよね、そうすると結局はUI層がInfra層の知識を知ってしまうことになりますので 🤔 

まあ最終的にはバランスのことなので、今回の課題のような簡単なアプリでしたらそれも大きな問題にはならないと思いますが、「本物の業務の体験」と言う目的でしたら、実際の業務ではこのような責務の肥大化は基本避ける方向のはずですので、あまり好ましくないと思います 🤔

2021-04-02 04:20 UTC, el-hoshino commented on YumemiTraining/Model/WeatherUseCase.swift
> +            return .success(makeWeatherOfJson(weatherJsonString: weatherJsonString))
戻り値の一貫性の意味では、例えば `makeWeatherOfJson` メソッドを下のエラーハンドリングに合わせて `Result` 返すのは一貫性はあります；ただここで違和感を覚えるのは、`makeWeatherOfJson` は `Weather` だけ返してるのに、下のエラーハンドリングの部分では特に `.success` を返すことはないにもかかわらず `Result` を返していることに、処理の一貫性が欠けてることですかね 🤔

2021-04-02 04:39 UTC, Syunprograming1 commented on YumemiTraining/Model/WeatherUseCase.swift
> +            return .success(makeWeatherOfJson(weatherJsonString: weatherJsonString))
なるほどです。
Resultを返しているのに.success と.failureが片方しかないのが不自然な感じってことですね。

2021-04-02 04:48 UTC, el-hoshino approved these changes
あとは細かいところですので、時間ある時に対応していただければOKです；

また、全体的についてですが、PR出す前に、一回自分で差分をチェックしておきましょう；ローカルで一度に全ての差分を確認するのはちょっと手間かかるかもしれませんが、GitHubならPR出してSubmitする前に、一度 `Files changed` タブを確認しておけば、差分が全部出ますので、そこでネーミングや一貫性などについて確認しておくといいでしょう

![LGTM](https://i.lgtm.fun/1cbj.png)

2021-04-02 04:48 UTC, el-hoshino commented on YumemiTraining/Model/WeatherResponse.swift
> +    enum WeatherKind: String, Decodable {
[nits]
逆にこれはアプリ全体で使うものなので `Response` 内で定義しない方無難です；

また、どっちかというと `WeatherType` の方が英語的に伝わりやすいですが、私が昨日指摘したときは `Weather` の中に入れるなら `WeatherType` の名前ですと `Weather` が無意味に重複して冗長ですが、`Type` 自体はSwiftの予約語なので紛らわしいから類語の `Kind` を使いましたから、逆に言うと積極的に `WeatherKind` を使うメリットは特にないです

2021-04-02 04:48 UTC, el-hoshino commented on YumemiTraining/Model/WeatherResponse.swift
> +        var imageName: String {
[nits]
`imageName: String` で返すより、どうせ使うのは画像そのものなので `image: UIImage` で返した方が便利ですね（ただ `UIImage` を返すのに `import UIKit` する必要が出てくるから、`image` の返す `private extension Weather` 自体を画面のファイルに持っていくか、別途ファイル作って `typealias Image = UIImage` 書いてここで `var image: Image` 書く感じがベターです

2021-04-02 04:48 UTC, el-hoshino commented on YumemiTraining/Model/WeatherType.swift
> +//}
[nits]
必要なくなったものは、コメントアウトではなく削除した方がいいです；履歴はgitがあるので別に困ることはそれほどないですし、逆に残ると検索時のノイズになるのでむしろデメリットの方が大きいです

2021-04-02 04:48 UTC, el-hoshino commented on YumemiTraining/Model/WeatherUseCase.swift
>              fatalError()
[nits]
今 `makeRequest` と `makeWeatherResponse` のエラーが投げられることがあるので、`catch YumemiWeatherError` だけでは不十分になって、ここで `fatalError()` にするとアプリが落ちる可能性が十分に出てきます

せっかくアラートの仕組み作ったから、`fatalError` ではなく、その仕組みをうまく使ってみましょう

2021-04-02 04:48 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +    private let date = "2020-04-01T12:00:00+09:00"
[nits]
今回の課題でなくても大丈夫ですので（と言うよりその仕組みを完全に把握するのは結構難しいので）、インターン終了後の宿題として `Date` と `String` の相互変換について調べてみましょう

2021-04-02 04:48 UTC, el-hoshino commented on YumemiTraining/ViewController.swift
> +    private func changeWeatherImage(WeatherResponse: WeatherResponse) {
[nits]
下の `changeWeatherTempLabel` は必要な引数（`minTemp` と `maxTemp`）だけ受け取っているのに対し、ここはそこまで必要としない `WeatherResponse` 全体を受け取っているのも一貫性に欠けていますね；ここで `WeatherKind` だけ受け取れば十分なはずです

2021-04-02 04:55 UTC, Syunprograming1 commented
レビューありがとうございます！
修正します

2021-04-02 05:23 UTC, merged

2021-04-05 14:17 UTC, ykws commented on YumemiTraining/Model/Area.swift
> +struct Area: Codable {
@el-hoshino 指摘ありがとうございます。 API 連携がぴんと来ていなくて、ネーミングに苦労しているようだったので Request/Response の指針があると良いかなと思った次第でしたが、折角 Infra層の役割を Model に持たせるように分けているので、

⬇️ このような方法を含めて例示すべきでした。

> それを内容ごとに（(weather: Weather, minTemp: Int, maTemp: Int) の感じで内容だけ伝えるとか、struct TempRange { var min: Int; var max: Int } 作って (weather: Weather, tempRange: TempRange) の感じで返すとかみたいな感じで、VC側でそのまま Request や Response を使わない形でやった方がいいでしょう